server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location = /demo {
        return 301 $scheme://$http_host/demo/;
    }

    location = /about-us {
        return 301 $scheme://$http_host/about-us/;
    }

    location = /privacy {
        return 301 $scheme://$http_host/privacy/;
    }

    location = /terms {
        return 301 $scheme://$http_host/terms/;
    }

    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
}
